### ISSUE TITLE
Do I still need landmarks if I have already cropped the faces on my side?

### ISSUE THREAD

**Issue by deepfakeLearnerHi** [megvii-research/FST-Matching#2]
Hello! I appreciate that you have released your source code and your trained mode. It is very nice of you! 

Meanwhile, I do find it a bit complicated when playing with it. In detail, I have some face images that I have already cropped them from some videos and they are all in square shapes. 

I wonder if I could directly run the testing code without inputting landmarks since I think the landmarks here are just for face cropping (please correct me if I am wrong).

**Comment by Nku-cs-dsc** [comment]
Hi, you can also directly test our model using your own cropped faces. However, to ensure that the pre-trained model performs consistently, we recommend that you test our model using the same data preprocessing settings.
